#Source all other files + window and workspace rules


#Monitor config
monitor=,preferred,auto,1


#Default programs
$terminal = kitty
$menu = wofi --show drun


source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/lookAndFeel.conf
