#All aesthetics-related config (borders and gaps, animations, etc.)


#Wallpapers
exec-once = swww-daemon --no-cache
exec-once = $HOME/.config/hypr/wallpapers/wallpapers.zsh


#Cursor size
env = XCURSOR_SIZE,20
env = HYPRCURSOR_SIZE,20


general {
    #Borders and gaps
    border_size = 3
    gaps_in = 0
    gaps_out = 0
    col.active_border = rgba(0044aaff) rgba(118844ff)
}


decoration {
    #Round corners
    rounding = 5

    #Dim and reduce opacity of inactive windows
    active_opacity = 1.0
    inactive_opacity = 0.9
    dim_inactive = true
    dim_strength = 0.7

    #Enable blur for transparent windows
    blur {
       enabled = true
       size = 3
       passes = 2
    }

    #Window shadows
    shadow {
       enabled = false
    }
}


animations {
    #Defining curves
    bezier = easeout,0,0.55,0.45,1      #Fast then slow
    bezier = linear,0,0,1,1             #Linear
    bezier = snap,1,0.1,0,0.9           #Snappy

    #Global fallback animation (slow to make it obvious when an animation is unset)
    animation = global, 1, 100, linear

    #Layers and popups
    animation = layers, 1, 3, easeout, popin 90%
    animation = fadeLayers, 1, 2, linear
    animation = fadePopups, 1, 1, linear

    #Windows
    animation = windows, 1, 3, easeout, popin 60%
    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear   
    animation = fadeDim, 1, 5, easeout
    animation = fadeSwitch, 1, 5, easeout
    animation = fadeShadow, 1, 5, easeout

    #Borders
    animation = border, 1, 2, linear
    animation = borderangle, 1, 30, linear

    #Switching workspaces
    animation = workspaces, 1, 2, easeout, slide

    #Disable startup zoom animation
    animation = monitorAdded, 0
}


misc {
    #Disable splash text and hyprland logo
    disable_hyprland_logo = true
    disable_splash_rendering = true 

    #Enable window swallowing
    enable_swallow = true
    swallow_regex = kitty    
}

#Disable window decorations for single-window workspaces
workspace = w[v1], decorate:false

#Tile all windows by default
windowrule = tile, class:.*

# Ignore maximize requests from apps.
windowrule = suppressevent maximize, class:.*
