general {
    # This runs on lock events like loginctl lock-session
    lock_cmd = pidof hyprlock || hyprlock

    # Lock screen before sleep
    before_sleep_cmd = loginctl lock-session
}

# Lower brightness after 2.5 minutes
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10%

    # Restore brightness
    on-resume = brightnessctl -r
}

# Lock screen after 3 minutes
listener {
    timeout = 180
    on-timeout = loginctl lock-session
}

# Turn off screen after 4 minutes
listener {
    timeout = 240
    on-timeout = brightnessctl set 0%
    on-resume = brightnessctl -r
}

# Suspend after 5 minutes
listener {
    timeout = 300
    on-timeout = systemctl suspend
}
