# Source all other files + window and workspace rules

# Monitor config
monitor=,preferred,auto,1

# Default programs
$terminal = kitty
$browser = firefox
#$fileExplorer = dolphin --sudo

# Login screen
exec-once = hyprlock || hyprctl dispatch exit

# Clipboard manager
exec-once = wl-paste --watch cliphist store

# Wallpaper manager
exec-once = awww-daemon --no-cache
exec-once = ~/.config/hypr/scripts/wallpaper_cycle.sh

# Battery level notification
exec-once = ~/.config/hypr/scripts/battery_notify.sh

# Polkit authentication daemon
exec-once = systemctl --user start hyprpolkitagent

# Screen blue light filter
exec-once = hyprsunset

# Idle manager daemon
exec-once = hypridle

# Source other config files
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/lookAndFeel.conf
source = ~/.config/hypr/configs/wrules.conf

