# Tile all windows by default and ignore maximize requests
windowrule = match:class .*, suppress_event maximize

# No gaps when only
workspace = w[tv1], gapsout:0, gapsin:0
windowrule = match:float false, match:workspace w[tv1], rounding 0, border_size 0
windowrule = match:float false, match:workspace f[1], border_size 0, rounding 0

# Float file picker windows
windowrule = match:class xdg-desktop-portal-gtk, float true, size 1000 700, decorate false

# Clipboard history window rules
windowrule = match:class clipboard-kitty, float true, size 800 600

# Fix an issue with Hyprshot including the selection border in screenshots
layerrule = match:namespace selection, no_anim true
